# Generated by Django 2.0.5 on 2018-05-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=512)),
                ('link', models.URLField()),
                ('repost', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='gates',
        ),
    ]
